languageCode = "en-us"
title = "Aerial"
baseurl = "http://example.org/"
theme = "aerial"

[params]
  name = "Adam Jensen"
  about = "Security Chief &nbsp;&bull;&nbsp; Cyborg &nbsp;&bull;&nbsp; Never asked for this"
  description = "Some description header text"
  language = "en"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"
#  googleanalytics = "UA-XXX-Y"

[[params.social]]
  medium = "Twitter"
  icon = "fab fa-twitter"
  link = "#"
  target = "_blank"

[[params.social]]
  medium = "Facebook"
  icon = "fab fa-facebook-f"
  link = "#"

[[params.social]]
  medium = "Dribbble"
  icon = "fab fa-dribbble"
  link = "#"

[[params.social]]
  medium = "Github"
  icon = "fab fa-github"
  link = "#"

[[params.social]]
  medium = "Email"
  icon = "far fa-envelope"
  link = "#"
